-- ============================================================
-- CARGA 1 - ACOMPANHAMENTOS COM INÍCIO ATÉ 2022
-- Executar as cargas em ordem: 1 -> 2 -> 3
-- A divisão considera a data de início do ACOMPANHAMENTO.
-- Os registros mensais acompanham a carga do respectivo acompanhamento.
-- ============================================================

-- MODALIDADE
INSERT INTO MODALIDADE (mod_id, mod_nome) VALUES (1, 'Híbrido');
INSERT INTO MODALIDADE (mod_id, mod_nome) VALUES (2, 'Online');
INSERT INTO MODALIDADE (mod_id, mod_nome) VALUES (3, 'Presencial');

-- MOTIVO_SAIDA
INSERT INTO MOTIVO_SAIDA (mot_id, mot_nome) VALUES (1, 'Alta');
INSERT INTO MOTIVO_SAIDA (mot_id, mot_nome) VALUES (2, 'Alta com Sessões Avulsas');
INSERT INTO MOTIVO_SAIDA (mot_id, mot_nome) VALUES (3, 'Apenas sessões avulsas');
INSERT INTO MOTIVO_SAIDA (mot_id, mot_nome) VALUES (4, 'Apenas uma vez');
INSERT INTO MOTIVO_SAIDA (mot_id, mot_nome) VALUES (5, 'Desistência');
INSERT INTO MOTIVO_SAIDA (mot_id, mot_nome) VALUES (6, 'Encaminhamento');
INSERT INTO MOTIVO_SAIDA (mot_id, mot_nome) VALUES (7, 'Falecimento');
INSERT INTO MOTIVO_SAIDA (mot_id, mot_nome) VALUES (8, 'Financeiro');
INSERT INTO MOTIVO_SAIDA (mot_id, mot_nome) VALUES (9, 'Indeterminado');
INSERT INTO MOTIVO_SAIDA (mot_id, mot_nome) VALUES (10, 'Pausa');

-- DIAGNOSTICO
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (1, 'Acompanhamento Terapêutico');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (2, 'Acompanhamento psicológico devido a um câncer');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (3, 'Alcoolismo');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (4, 'Alto Conhecimento');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (5, 'Ansiedade');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (6, 'Ansiedade + Autoconhecimento');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (7, 'Ansiedade + Depressão');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (8, 'Ansiedade + Relacionamento Afetivo');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (9, 'Ansiedade e Relac.');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (10, 'Autoconhecimento');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (11, 'Bipolar');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (12, 'Borderline');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (13, 'Burnout');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (14, 'Buscando Autoconhecimento');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (15, 'Dep. Emocional');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (16, 'Depressão');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (17, 'Depressão e Estresse');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (18, 'Depressão em Tratamento');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (19, 'Dermatilomania');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (20, 'Fase de Desenvolvimento');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (21, 'Fobia Social');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (22, 'Hipocondríaca');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (23, 'Insegurança');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (24, 'Luto');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (25, 'Obesidade');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (26, 'Orientação Vocacional');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (27, 'Pensamentos Invasivos');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (28, 'Perda de Emprego');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (29, 'Relacionamento');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (31, 'Relacionamento Afetivo');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (32, 'Relacionamento Afetivo + Insegurança');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (35, 'Relacionamento Familiar');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (36, 'Relacionamento Interpessoal');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (37, 'Separação');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (38, 'TDAH');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (39, 'Trabalho');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (40, 'Transição de Gênero do Filho');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (41, 'Trat. Câncer');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (42, 'Vai por demanda');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (43, 'Verificação de Diagnóstico de Autismo');
INSERT INTO DIAGNOSTICO (diag_id, diag_nome) VALUES (44, 'Indeterminado');

-- PACIENTE
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (6, 'Andre');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (14, 'Bianca Um');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (16, 'Caio');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (19, 'Camila 2');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (22, 'Carla Um');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (29, 'Eduardo');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (39, 'Gabriela');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (40, 'Gabriele');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (47, 'Isa');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (54, 'João Pedro');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (56, 'Jose');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (58, 'Laura');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (59, 'Leandra');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (61, 'Luana');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (63, 'Luiz');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (67, 'Mariluce');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (70, 'Matheus');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (72, 'Michelan');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (74, 'Milton');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (75, 'Mitsue');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (76, 'Mota');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (77, 'Natalia');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (78, 'Neli');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (82, 'Poliana');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (85, 'Regina');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (86, 'Renata 1');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (87, 'Renata 2');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (93, 'Samantha');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (96, 'Shophie');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (101, 'Sophia');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (105, 'Verônica');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (106, 'Victor');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (109, 'Yan');
INSERT INTO PACIENTE (pac_id, pac_nome) VALUES (112, 'Yumi');

-- ACOMPANHAMENTO
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (6, 1, TO_DATE('01/05/2022','DD/MM/YYYY'), NULL, 6, NULL, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (14, 0, TO_DATE('01/05/2022','DD/MM/YYYY'), TO_DATE('01/07/2024','DD/MM/YYYY'), 14, 1, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (16, 0, TO_DATE('01/05/2020','DD/MM/YYYY'), TO_DATE('01/04/2023','DD/MM/YYYY'), 16, 1, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (19, 0, TO_DATE('01/05/2022','DD/MM/YYYY'), TO_DATE('01/02/2024','DD/MM/YYYY'), 19, 1, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (22, 1, TO_DATE('01/05/2018','DD/MM/YYYY'), NULL, 22, NULL, 1);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (29, 0, TO_DATE('01/01/2021','DD/MM/YYYY'), TO_DATE('01/07/2023','DD/MM/YYYY'), 29, 8, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (39, 1, TO_DATE('01/05/2019','DD/MM/YYYY'), NULL, 39, NULL, 1);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (40, 0, TO_DATE('01/05/2022','DD/MM/YYYY'), TO_DATE('01/07/2025','DD/MM/YYYY'), 40, 6, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (47, 0, TO_DATE('02/01/2021','DD/MM/YYYY'), TO_DATE('01/06/2024','DD/MM/YYYY'), 47, 1, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (54, 0, TO_DATE('01/06/2019','DD/MM/YYYY'), TO_DATE('01/07/2025','DD/MM/YYYY'), 54, 8, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (56, 1, TO_DATE('01/05/2021','DD/MM/YYYY'), NULL, 56, NULL, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (58, 0, TO_DATE('01/05/2022','DD/MM/YYYY'), TO_DATE('01/05/2023','DD/MM/YYYY'), 58, 1, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (59, 0, TO_DATE('01/04/2022','DD/MM/YYYY'), TO_DATE('01/04/2026','DD/MM/YYYY'), 59, 6, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (61, 1, TO_DATE('01/06/2020','DD/MM/YYYY'), NULL, 61, NULL, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (63, 1, TO_DATE('01/10/2021','DD/MM/YYYY'), NULL, 63, NULL, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (67, 1, TO_DATE('03/03/2019','DD/MM/YYYY'), NULL, 67, NULL, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (70, 1, TO_DATE('01/05/2020','DD/MM/YYYY'), NULL, 70, NULL, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (72, 1, TO_DATE('01/05/2021','DD/MM/YYYY'), NULL, 72, NULL, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (74, 0, TO_DATE('02/05/2022','DD/MM/YYYY'), TO_DATE('03/01/2023','DD/MM/YYYY'), 74, 1, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (75, 0, TO_DATE('02/02/2021','DD/MM/YYYY'), NULL, 75, 1, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (76, 0, TO_DATE('02/02/2021','DD/MM/YYYY'), TO_DATE('01/03/2023','DD/MM/YYYY'), 75, 9, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (77, 0, TO_DATE('10/05/2022','DD/MM/YYYY'), TO_DATE('01/06/2024','DD/MM/YYYY'), 76, 1, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (78, 1, TO_DATE('03/04/2018','DD/MM/YYYY'), NULL, 77, 9, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (79, 0, TO_DATE('03/08/2022','DD/MM/YYYY'), TO_DATE('02/06/2023','DD/MM/YYYY'), 78, 8, 2);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (83, 0, TO_DATE('15/06/2021','DD/MM/YYYY'), TO_DATE('02/01/2023','DD/MM/YYYY'), 82, 6, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (86, 0, TO_DATE('08/07/2021','DD/MM/YYYY'), TO_DATE('03/06/2026','DD/MM/YYYY'), 85, 1, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (88, 1, TO_DATE('24/04/2021','DD/MM/YYYY'), NULL, 86, 9, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (89, 0, TO_DATE('08/07/2017','DD/MM/YYYY'), TO_DATE('03/09/2024','DD/MM/YYYY'), 87, 1, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (95, 1, TO_DATE('03/05/2018','DD/MM/YYYY'), NULL, 93, 9, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (98, 0, TO_DATE('12/12/2022','DD/MM/YYYY'), TO_DATE('03/02/2023','DD/MM/YYYY'), 96, 6, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (103, 0, TO_DATE('08/04/2020','DD/MM/YYYY'), TO_DATE('25/06/2023','DD/MM/YYYY'), 101, 6, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (107, 0, TO_DATE('20/02/2020','DD/MM/YYYY'), TO_DATE('07/01/2023','DD/MM/YYYY'), 105, 1, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (108, 0, TO_DATE('12/08/2021','DD/MM/YYYY'), TO_DATE('15/02/2023','DD/MM/YYYY'), 106, 1, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (111, 0, TO_DATE('08/06/2022','DD/MM/YYYY'), TO_DATE('03/02/2025','DD/MM/YYYY'), 109, 10, 3);
INSERT INTO ACOMPANHAMENTO (aco_id, aco_status, aco_data_inicio, aco_data_fim, PACIENTE_pac_id, MOTIVO_SAIDA_mot_id, MODALIDADE_mod_id) VALUES (114, 0, TO_DATE('06/12/2022','DD/MM/YYYY'), TO_DATE('29/09/2025','DD/MM/YYYY'), 112, 1, 2);

-- ACOMPANHAMENTO_DIAGNOSTICO
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (1, 6);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (29, 14);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (16, 16);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (26, 19);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (10, 22);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (29, 29);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (5, 39);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (12, 40);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (5, 47);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (20, 54);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (31, 56);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (24, 58);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (16, 59);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (21, 61);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (27, 63);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (10, 67);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (6, 70);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (16, 72);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (13, 74);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (31, 75);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (31, 76);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (16, 77);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (4, 78);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (5, 79);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (5, 83);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (9, 86);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (29, 88);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (19, 89);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (10, 95);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (16, 98);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (12, 103);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (35, 107);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (16, 108);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (31, 111);
INSERT INTO ACOMPANHAMENTO_DIAGNOSTICO (DIAGNOSTICO_diag_id, ACOMPANHAMENTO_aco_id) VALUES (35, 114);

-- ACOMPANHAMENTO_MENSAL
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (29, TO_DATE('06/01/2024','DD/MM/YYYY'), 4, 0, 460.00, 6);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (30, TO_DATE('07/01/2024','DD/MM/YYYY'), 2, 0, 310.00, 6);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (31, TO_DATE('03/01/2025','DD/MM/YYYY'), 2, 0, 310.00, 6);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (32, TO_DATE('07/01/2025','DD/MM/YYYY'), 2, 0, 310.00, 6);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (33, TO_DATE('03/01/2026','DD/MM/YYYY'), 1, 0, 215.00, 6);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (34, TO_DATE('05/01/2026','DD/MM/YYYY'), 1, 0, 215.00, 6);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (53, TO_DATE('06/01/2024','DD/MM/YYYY'), 1, 0, 150.00, 14);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (54, TO_DATE('07/01/2024','DD/MM/YYYY'), 3, 0, 150.00, 14);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (56, TO_DATE('01/03/2023','DD/MM/YYYY'), 2, 0, 220.00, 16);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (57, TO_DATE('01/04/2023','DD/MM/YYYY'), 3, 1, 230.00, 16);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (58, TO_DATE('01/05/2023','DD/MM/YYYY'), 3, 0, 240.00, 16);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (67, TO_DATE('01/03/2023','DD/MM/YYYY'), 1, 0, 120.00, 19);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (68, TO_DATE('01/06/2023','DD/MM/YYYY'), 1, 0, 155.00, 19);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (69, TO_DATE('01/07/2023','DD/MM/YYYY'), 1, 0, 155.00, 19);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (76, TO_DATE('06/01/2024','DD/MM/YYYY'), 1, 0, 150.00, 22);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (77, TO_DATE('07/01/2024','DD/MM/YYYY'), 2, 0, 150.00, 22);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (78, TO_DATE('03/01/2025','DD/MM/YYYY'), 2, 0, 150.00, 22);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (79, TO_DATE('07/01/2025','DD/MM/YYYY'), 2, 0, 150.00, 22);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (80, TO_DATE('03/01/2026','DD/MM/YYYY'), 2, 0, 340.00, 22);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (81, TO_DATE('05/01/2026','DD/MM/YYYY'), 2, 0, 340.00, 22);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (95, TO_DATE('01/01/2023','DD/MM/YYYY'), 1, 0, 530.00, 29);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (96, TO_DATE('01/02/2023','DD/MM/YYYY'), 1, 0, 300.00, 29);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (97, TO_DATE('01/02/2023','DD/MM/YYYY'), 2, 0, 300.00, 29);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (98, TO_DATE('01/03/2023','DD/MM/YYYY'), 4, 0, 600.00, 29);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (99, TO_DATE('01/05/2023','DD/MM/YYYY'), 2, 1, 560.00, 29);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (100, TO_DATE('01/07/2023','DD/MM/YYYY'), 5, 4, 200.00, 29);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (146, TO_DATE('07/01/2025','DD/MM/YYYY'), 3, 0, 0.00, 39);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (147, TO_DATE('06/01/2024','DD/MM/YYYY'), 2, 0, 310.00, 39);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (148, TO_DATE('07/01/2024','DD/MM/YYYY'), 4, 0, 460.00, 39);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (149, TO_DATE('03/01/2025','DD/MM/YYYY'), 4, 0, 460.00, 39);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (150, TO_DATE('07/01/2025','DD/MM/YYYY'), 2, 0, 310.00, 39);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (151, TO_DATE('03/01/2026','DD/MM/YYYY'), 2, 0, 340.00, 39);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (152, TO_DATE('05/01/2026','DD/MM/YYYY'), 2, 0, 340.00, 39);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (153, TO_DATE('06/01/2024','DD/MM/YYYY'), 2, 0, 310.00, 40);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (154, TO_DATE('07/01/2024','DD/MM/YYYY'), 2, 0, 275.00, 40);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (155, TO_DATE('01/02/2023','DD/MM/YYYY'), 1, 0, 115.00, 40);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (156, TO_DATE('01/03/2023','DD/MM/YYYY'), 5, 1, 460.00, 40);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (157, TO_DATE('01/07/2023','DD/MM/YYYY'), 2, 0, 300.00, 40);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (158, TO_DATE('06/01/2024','DD/MM/YYYY'), 4, 0, 460.00, 40);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (159, TO_DATE('07/01/2024','DD/MM/YYYY'), 4, 0, 460.00, 40);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (160, TO_DATE('03/01/2025','DD/MM/YYYY'), 4, 0, 460.00, 40);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (161, TO_DATE('07/01/2025','DD/MM/YYYY'), 4, 0, 460.00, 40);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (162, TO_DATE('01/01/2023','DD/MM/YYYY'), 4, 0, 460.00, 40);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (163, TO_DATE('01/02/2023','DD/MM/YYYY'), 1, 0, 115.00, 40);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (164, TO_DATE('01/03/2023','DD/MM/YYYY'), 4, 2, 460.00, 40);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (165, TO_DATE('01/04/2023','DD/MM/YYYY'), 4, 1, 345.00, 40);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (180, TO_DATE('01/03/2023','DD/MM/YYYY'), 1, 0, 200.00, 47);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (181, TO_DATE('01/04/2023','DD/MM/YYYY'), 1, 0, 200.00, 47);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (182, TO_DATE('01/05/2023','DD/MM/YYYY'), 2, 0, 300.00, 47);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (183, TO_DATE('06/01/2024','DD/MM/YYYY'), 1, 0, 150.00, 47);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (198, TO_DATE('06/01/2024','DD/MM/YYYY'), 1, 0, 150.00, 54);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (199, TO_DATE('07/01/2024','DD/MM/YYYY'), 1, 0, 150.00, 54);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (200, TO_DATE('03/01/2025','DD/MM/YYYY'), 1, 0, 150.00, 54);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (201, TO_DATE('07/01/2025','DD/MM/YYYY'), 1, 0, 150.00, 54);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (208, TO_DATE('03/01/2025','DD/MM/YYYY'), 1, 0, 200.00, 56);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (209, TO_DATE('07/01/2025','DD/MM/YYYY'), 1, 0, 200.00, 56);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (210, TO_DATE('03/01/2026','DD/MM/YYYY'), 2, 0, 340.00, 56);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (211, TO_DATE('05/01/2026','DD/MM/YYYY'), 2, 0, 340.00, 56);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (212, TO_DATE('01/04/2023','DD/MM/YYYY'), 1, 0, 150.00, 56);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (213, TO_DATE('01/05/2023','DD/MM/YYYY'), 1, 0, 150.00, 56);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (215, TO_DATE('01/03/2023','DD/MM/YYYY'), 1, 0, 300.00, 58);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (216, TO_DATE('06/01/2024','DD/MM/YYYY'), 2, 0, 310.00, 59);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (217, TO_DATE('07/01/2024','DD/MM/YYYY'), 1, 0, 200.00, 59);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (218, TO_DATE('07/01/2025','DD/MM/YYYY'), 1, 0, 0.00, 59);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (224, TO_DATE('01/02/2023','DD/MM/YYYY'), 2, 0, 260.00, 61);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (225, TO_DATE('01/03/2023','DD/MM/YYYY'), 2, 0, 260.00, 61);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (226, TO_DATE('01/05/2023','DD/MM/YYYY'), 2, 0, 260.00, 61);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (227, TO_DATE('07/01/2024','DD/MM/YYYY'), 1, 4, 0.00, 61);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (228, TO_DATE('03/01/2025','DD/MM/YYYY'), 1, 0, 0.00, 61);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (229, TO_DATE('07/01/2025','DD/MM/YYYY'), 1, 0, 0.00, 61);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (230, TO_DATE('03/01/2026','DD/MM/YYYY'), 1, 4, 0.00, 61);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (231, TO_DATE('05/01/2026','DD/MM/YYYY'), 1, 0, 215.00, 61);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (237, TO_DATE('01/03/2023','DD/MM/YYYY'), 1, 0, 200.00, 63);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (238, TO_DATE('01/03/2023','DD/MM/YYYY'), 2, 0, 270.00, 63);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (239, TO_DATE('01/04/2023','DD/MM/YYYY'), 1, 0, 200.00, 63);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (240, TO_DATE('06/01/2024','DD/MM/YYYY'), 2, 0, 310.00, 63);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (241, TO_DATE('07/01/2024','DD/MM/YYYY'), 4, 0, 460.00, 63);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (242, TO_DATE('03/01/2025','DD/MM/YYYY'), 2, 0, 310.00, 63);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (243, TO_DATE('03/01/2026','DD/MM/YYYY'), 1, 0, 215.00, 63);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (244, TO_DATE('05/01/2026','DD/MM/YYYY'), 2, 0, 310.00, 63);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (245, TO_DATE('05/01/2026','DD/MM/YYYY'), 1, 0, 215.00, 63);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (253, TO_DATE('07/01/2024','DD/MM/YYYY'), 1, 0, 200.00, 67);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (254, TO_DATE('06/01/2024','DD/MM/YYYY'), 1, 0, 200.00, 67);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (255, TO_DATE('07/01/2024','DD/MM/YYYY'), 1, 0, 200.00, 67);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (256, TO_DATE('03/01/2025','DD/MM/YYYY'), 1, 0, 200.00, 67);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (257, TO_DATE('07/01/2025','DD/MM/YYYY'), 1, 0, 200.00, 67);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (258, TO_DATE('03/01/2026','DD/MM/YYYY'), 1, 0, 215.00, 67);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (259, TO_DATE('05/01/2026','DD/MM/YYYY'), 1, 0, 215.00, 67);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (260, TO_DATE('06/01/2026','DD/MM/YYYY'), 1, 0, 100.00, 67);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (266, TO_DATE('01/03/2023','DD/MM/YYYY'), 2, 0, 230.00, 70);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (267, TO_DATE('01/03/2023','DD/MM/YYYY'), 3, 0, 345.00, 70);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (268, TO_DATE('01/04/2023','DD/MM/YYYY'), 4, 1, 345.00, 70);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (269, TO_DATE('01/05/2023','DD/MM/YYYY'), 2, 0, 230.00, 70);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (270, TO_DATE('01/07/2023','DD/MM/YYYY'), 5, 2, 115.00, 70);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (271, TO_DATE('06/01/2024','DD/MM/YYYY'), 4, 0, 460.00, 70);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (272, TO_DATE('07/01/2024','DD/MM/YYYY'), 2, 0, 310.00, 70);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (273, TO_DATE('03/01/2025','DD/MM/YYYY'), 2, 0, 310.00, 70);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (274, TO_DATE('07/01/2025','DD/MM/YYYY'), 2, 0, 310.00, 70);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (275, TO_DATE('03/01/2026','DD/MM/YYYY'), 2, 0, 340.00, 70);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (276, TO_DATE('05/01/2026','DD/MM/YYYY'), 2, 0, 340.00, 70);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (283, TO_DATE('01/03/2023','DD/MM/YYYY'), 1, 0, 150.00, 72);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (284, TO_DATE('01/03/2023','DD/MM/YYYY'), 1, 0, 150.00, 72);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (285, TO_DATE('01/04/2023','DD/MM/YYYY'), 2, 1, 150.00, 72);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (286, TO_DATE('01/05/2023','DD/MM/YYYY'), 2, 0, 300.00, 72);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (287, TO_DATE('01/06/2023','DD/MM/YYYY'), 1, 0, 200.00, 72);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (288, TO_DATE('01/07/2023','DD/MM/YYYY'), 1, 0, 200.00, 72);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (289, TO_DATE('01/08/2023','DD/MM/YYYY'), 1, 0, 200.00, 72);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (290, TO_DATE('06/01/2024','DD/MM/YYYY'), 1, 0, 0.00, 72);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (291, TO_DATE('07/01/2024','DD/MM/YYYY'), 1, 0, 0.00, 72);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (292, TO_DATE('03/01/2025','DD/MM/YYYY'), 1, 0, 0.00, 72);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (293, TO_DATE('07/01/2025','DD/MM/YYYY'), 2, 0, 0.00, 72);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (294, TO_DATE('03/01/2026','DD/MM/YYYY'), 1, 0, 0.00, 72);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (295, TO_DATE('05/01/2026','DD/MM/YYYY'), 1, 0, 0.00, 72);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (302, TO_DATE('01/03/2023','DD/MM/YYYY'), 1, 0, 345.00, 74);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (303, TO_DATE('01/03/2023','DD/MM/YYYY'), 4, 2, 230.00, 74);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (304, TO_DATE('01/01/2023','DD/MM/YYYY'), 2, 0, 270.00, 75);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (305, TO_DATE('01/02/2023','DD/MM/YYYY'), 2, 0, 270.00, 75);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (306, TO_DATE('01/03/2023','DD/MM/YYYY'), 1, 0, 105.00, 76);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (307, TO_DATE('01/03/2023','DD/MM/YYYY'), 2, 0, 200.00, 76);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (308, TO_DATE('01/03/2023','DD/MM/YYYY'), 2, 0, 270.00, 76);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (309, TO_DATE('06/01/2024','DD/MM/YYYY'), 1, 0, 0.00, 75);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (310, TO_DATE('06/01/2024','DD/MM/YYYY'), 1, 0, 200.00, 77);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (311, TO_DATE('01/05/2023','DD/MM/YYYY'), 1, 0, 200.00, 78);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (312, TO_DATE('07/01/2024','DD/MM/YYYY'), 1, 0, 0.00, 78);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (313, TO_DATE('03/01/2025','DD/MM/YYYY'), 1, 0, 0.00, 78);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (314, TO_DATE('07/01/2025','DD/MM/YYYY'), 1, 0, 0.00, 78);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (315, TO_DATE('03/01/2026','DD/MM/YYYY'), 1, 0, 0.00, 78);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (316, TO_DATE('05/01/2026','DD/MM/YYYY'), 1, 0, 0.00, 78);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (317, TO_DATE('01/03/2023','DD/MM/YYYY'), 1, 0, 110.00, 79);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (326, TO_DATE('01/03/2023','DD/MM/YYYY'), 1, 0, 100.00, 83);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (331, TO_DATE('01/01/2023','DD/MM/YYYY'), 2, 1, 120.00, 86);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (332, TO_DATE('01/02/2023','DD/MM/YYYY'), 2, 1, 150.00, 86);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (333, TO_DATE('01/03/2023','DD/MM/YYYY'), 2, 0, 300.00, 86);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (334, TO_DATE('06/01/2024','DD/MM/YYYY'), 2, 0, 310.00, 86);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (335, TO_DATE('07/01/2024','DD/MM/YYYY'), 1, 0, 200.00, 86);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (336, TO_DATE('03/01/2025','DD/MM/YYYY'), 1, 0, 200.00, 86);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (337, TO_DATE('07/01/2025','DD/MM/YYYY'), 1, 0, 200.00, 86);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (339, TO_DATE('01/01/2023','DD/MM/YYYY'), 2, 0, 300.00, 88);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (340, TO_DATE('01/02/2023','DD/MM/YYYY'), 2, 1, 150.00, 88);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (341, TO_DATE('01/03/2023','DD/MM/YYYY'), 2, 1, 150.00, 88);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (342, TO_DATE('01/03/2023','DD/MM/YYYY'), 2, 1, 130.00, 89);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (343, TO_DATE('01/04/2023','DD/MM/YYYY'), 2, 0, 260.00, 89);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (344, TO_DATE('06/01/2024','DD/MM/YYYY'), 1, 0, 200.00, 89);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (345, TO_DATE('07/01/2024','DD/MM/YYYY'), 2, 0, 310.00, 89);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (346, TO_DATE('03/01/2025','DD/MM/YYYY'), 1, 0, 200.00, 89);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (347, TO_DATE('07/01/2024','DD/MM/YYYY'), 1, 0, 200.00, 89);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (348, TO_DATE('03/01/2026','DD/MM/YYYY'), 1, 0, 0.00, 89);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (349, TO_DATE('05/01/2026','DD/MM/YYYY'), 1, 0, 0.00, 89);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (373, TO_DATE('01/01/2023','DD/MM/YYYY'), 1, 0, 150.00, 95);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (374, TO_DATE('01/02/2023','DD/MM/YYYY'), 1, 0, 75.00, 95);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (375, TO_DATE('01/03/2023','DD/MM/YYYY'), 1, 0, 150.00, 95);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (381, TO_DATE('01/06/2023','DD/MM/YYYY'), 2, 0, 350.00, 98);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (382, TO_DATE('01/07/2023','DD/MM/YYYY'), 4, 0, 460.00, 98);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (401, TO_DATE('01/01/2023','DD/MM/YYYY'), 1, 0, 100.00, 103);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (406, TO_DATE('01/02/2023','DD/MM/YYYY'), 1, 0, 180.00, 107);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (407, TO_DATE('01/02/2023','DD/MM/YYYY'), 2, 0, 360.00, 107);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (408, TO_DATE('01/03/2023','DD/MM/YYYY'), 1, 0, 180.00, 107);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (409, TO_DATE('01/03/2023','DD/MM/YYYY'), 2, 0, 470.00, 107);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (410, TO_DATE('01/06/2023','DD/MM/YYYY'), 2, 0, 230.00, 107);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (411, TO_DATE('01/12/2023','DD/MM/YYYY'), 1, 0, 640.00, 107);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (412, TO_DATE('01/02/2023','DD/MM/YYYY'), 1, 0, 115.00, 108);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (413, TO_DATE('01/03/2023','DD/MM/YYYY'), 1, 0, 115.00, 108);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (414, TO_DATE('01/03/2023','DD/MM/YYYY'), 2, 0, 240.00, 108);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (418, TO_DATE('01/02/2023','DD/MM/YYYY'), 2, 0, 305.00, 111);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (419, TO_DATE('03/01/2025','DD/MM/YYYY'), 1, 0, 155.00, 111);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (420, TO_DATE('03/02/2025','DD/MM/YYYY'), 1, 0, 150.00, 111);
INSERT INTO ACOMPANHAMENTO_MENSAL (men_id, men_periodo, men_vezes_mes, men_vezes_falta, men_valor_mensal, ACOMPANHAMENTO_aco_id) VALUES (426, TO_DATE('01/03/2023','DD/MM/YYYY'), 3, 0, 430.00, 114);

COMMIT;
